### ISSUE TITLE
Problem getting tracks, may be me 

### ISSUE THREAD

**Issue by quatre432** [microlinkhq/spotify-url-info#100]
when trying to gettracks i receieve the following error 

SyntaxError: Unexpected token e in JSON at position 0
    at JSON.parse (<anonymous>)
    at C:\node_modules\spotify-url-info\src\index.js:36:18

**Spotify URL(s)**
(https://open.spotify.com/playlist/37i9dQZF1E37tA0YCiV36c?si=d13a383ec4294e07)

**Your Code**
try{
		  let songs = await getTracks(args[1]);
		  }
		  catch(err)
		  {
			  console.log(err);
		  }

i was using a older version i believe on discord.js v12 and im having to update everything i used to call 

let songs = await spAPI.getTracks(args[1]);

**Comment by Kikobeats** [comment]
Can you try https://github.com/microlinkhq/spotify-url-info/releases/tag/v3.1.6 ?

**Comment by quatre432** [comment]
Yeah I download that version as well as some older ones and I am getting the same error

**Comment by Kikobeats** [comment]
shipped https://github.com/microlinkhq/spotify-url-info/releases/tag/v3.1.7 that should address your issue.

Can you confirm?

**Comment by quatre432** [comment]
Looks like it, thanks a lot
