### ISSUE TITLE
not able to fetch

### ISSUE THREAD

**Issue by rajamoulimallareddy** [microlinkhq/spotify-url-info#104]
Error: Couldn't find any data in embed page that we know how to parse

**Comment by Kikobeats** [comment]
Hello,

That is expected in case you provide a non spotify URL

https://github.com/microlinkhq/spotify-url-info/blob/95d07a5de69541fd781540879a5aa6e19088495d/src/index.js#L51

**Comment by rajamoulimallareddy** [comment]
well the link is correct but idk how to import using typescript
