### ISSUE TITLE
Providing a Spotify link to a deleted track or playlist crashes the app

### ISSUE THREAD

**Issue by abaza738** [microlinkhq/spotify-url-info#105]
**Describe the bug**
When providing a link to an old playlist or track that has since been removed or deleted, the library would crash the app.  
If I'm not mistaken, when trying to access the `html` element of the page (which doesn't exist when the playlist doesn't exist) the `.children` property is being accessed from an `undefined` result of the `.find` method.
This happens in line [26](https://github.com/microlinkhq/spotify-url-info/blob/dc64a2d3cc1b2385ceb57ab37d90138511b4d372/src/index.js#L26) in `index.js`.

**Spotify URL(s)**
[The specific Spotify URL you are having issues with.](https://open.spotify.com/playlist/7E6aXqOtSnwECFLiCosTmM?si=09d0d64072e54e58&nd=1)

**Your Code**
I am currently using the `getData` method as follows:
```ts
getTracks(url: string) {
  try {
    data = await getData(url);
  } catch (e) {
    console.log(e);
    return;
  }
}
```

**Error Message**
```
TypeError: Cannot read properties of undefined (reading 'children')
    at [REDACTED]\node_modules\spotify-url-info\src\index.js:27:5
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Function.getTracks ([REDACTED]/spotify.ts:20:20)
```

Thank you.

**Comment by abaza738** [comment]
Possibly related: #68 and #66.

**Comment by Kikobeats** [comment]
Thanks for reporting; Can you confirm v3.1.9 addressed the issue?

**Comment by abaza738** [comment]
You're welcome, thanks for the quick solve!  
As far as I can tell, it's working now.

Appreciate your help!
