### ISSUE TITLE
TypeError: Couldn't find scripts to get the data.

### ISSUE THREAD

**Issue by Pudochu** [microlinkhq/spotify-url-info#111]
TypeError: Couldn't find scripts to get the data.
Please report the problem at https://github.com/microlinkhq/spotify-url-info/iss
ues.
    at throwError (C:\Users\Administrator\Desktop\Spotify\node_modules\spotify
-url-info\src\index.js:22:9)
    at C:\Users\Administrator\Desktop\Spotify\node_modules\spotify-url-info\sr
c\index.js:37:37
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5
)

**Comment by Pudochu** [comment]
This error occurs when you write "googlebot" as "user-agent" in the Headers section.
('user-agent': 'googlebot')

**Comment by Kikobeats** [comment]
Then don't user 'googlebot' as user-agent? 😅
