### ISSUE TITLE
Spotify URL(s) Spotify Playlist is not playing

### ISSUE THREAD

**Issue by sakib-ahmmed** [microlinkhq/spotify-url-info#117]
**Describe the bug**

**Spotify URL(s)**
The specific spotify URLs you are having issues with. Even If it's broken for all URLs, please put at least one that caused an error.

**Your Code**
The part of your code where you use the functions you imported from the library and the surrounding lines / function.

**Error Message**
The error message you get when running the code.

**Comment by Kikobeats** [comment]
Sorry, but this is a bad an issue report, no info or way to reproduce it  ☹️
