### ISSUE TITLE
It is neither possible to get the release date of a song/album nor distinguish between an album and a single

### ISSUE THREAD

**Issue by Tony450** [microlinkhq/spotify-url-info#118]
## Bug description

Hello everyone,

I have used this library since August, 2022 and I haven't had any problems until January approximately. Right now, I have the following problems:

1. It is not possible to get the release date of any song/album. The JSON object returned by the library has always a null value in this field.

2. It is not possible to know if a parsed url contains either a single song or an album whereas some months ago, with older versions, it was by checking the field "album_type" of the JSON object. This field has currently disappeared.

In order to solve the problem, I thought that to get the information with the format I needed, using an old version was possible, however, it is neither possible due to the fact that the error message "Couldn't find any data in embed page that we know how to parse" appears when I use a version previous to 3.1.4 (which was the version that I used without any problems).

An example of what I am explaining is below, with the url specified I get the JSON object that is shown here (with a null release date and without any "album_type" field):

### Spotify URL(s)

https://open.spotify.com/album/0akDdsW5I5D6ZpQU4B6Kre?highlight=spotify:track:4raY0xxADxSo4sachP0rFr

### JSON object obtanied

{
	type: "album",
	name: "Quasi",
	uri: "spotify:album:0akDdsW5I5D6ZpQU4B6Kre",
	id: "0akDdsW5I5D6ZpQU4B6Kre",
	title: "Quasi",
	subtitle: "Pablo López",
	coverArt: {
	  extractedColors: {
		colorDark: {
		  hex: "#2080A0",
		},
	  },
	  sources: [
		{
		  height: 640,
		  width: 640,
		  url: "https://i.scdn.co/image/ab67616d0000b2732e16e335d5e8aba0a80086d5",
		},
		{
		  height: 300,
                  width: 300,
		  url: "https://i.scdn.co/image/ab67616d00001e022e16e335d5e8aba0a80086d5",
		},
		{
		  height: 64,
		  width: 64,
		  url: "https://i.scdn.co/image/ab67616d000048512e16e335d5e8aba0a80086d5",
		},
	  ],
	},
	releaseDate: null,
	duration: 0,
	maxDuration: 0,
	isPlayable: true,
	isExplicit: false,
	hasVideo: false,
	relatedEntityUri: "",
	trackList: [
	  {
		uri: "spotify:track:4raY0xxADxSo4sachP0rFr",
		uid: "12608b072eae0f6d2ab1",
		title: "Quasi",
		subtitle: "Pablo López",
		isExplicit: false,
		duration: 209700,
		isPlayable: true,
		audioPreview: {
		  format: "MP3_96",
		  url: "https://p.scdn.co/mp3-preview/325857d492a70bcc97c19aa93290b1bbd82bc0d8",
		},
	  },
	],
}

I don't know if this happens due to spotify changes, but is there a solution? Could I get the information I need by doing something different? 

I would be grateful if someone could help me with this problem, this library is very helpful and I really need it to let a Mp3Tagger program I have developed to work.

Regards.

**Comment by Kikobeats** [comment]
Yep, I also noted that. It looks like isn't possible, date is not anymore there ☹️

**Comment by Kikobeats** [comment]
Yep, I also noted that. It looks like isn't possible, date is not anymore there ☹️
