### ISSUE TITLE
getTracks limit

### ISSUE THREAD

**Issue by Raiper34** [microlinkhq/spotify-url-info#132]
Hi,

As I know, `getTracks` has a limit of 100 tracks, why is it and is there any possibility to get all songs from playlist, when playlist contains 2000 tracks?

**Comment by Kikobeats** [comment]
Hello,

That's happening because Spotify is using Next.js and it's returning the first 100 tracks, and after that, returning the rest of tracks, and this library is just performing a simple HTTP GET for getting the content behind a Spotify URL.
