### ISSUE TITLE
Error: Couldn't parse undefined as valid URL

### ISSUE THREAD

**Issue by Muh9049** [microlinkhq/spotify-url-info#66]
I am once again getting this issue after thinking it fixed but looks like it isn't. It only seems to happen rarely with certain Spotify links.

The error is this: https://sourceb.in/7gRDD1d1zU

**Comment by DaStormer** [comment]
For context, it seems to be happening with unavailable tracks.

Example: 
![image](https://user-images.githubusercontent.com/40336269/104495655-0a429580-55a6-11eb-8c6c-78b3dd0f2f55.png)


Can this be error handled somehow?

**Comment by karlsander** [comment]
Please post a specific URL where this applies.

**Comment by muhimur9049** [comment]
For example this one: https://open.spotify.com/playlist/2aVn3d3TCsxjXaK3F6ETiM?si=7IQO-CTuRnqOYSfLhoDUIQ

**Comment by muhimur9049** [comment]
@karlsander This repository/library seems to be very inactive, especially in the issues section. Could we get any sort of estimate of when this will be fixed perhaps?

(The playlist link above has some unavailable songs which causes the error)
