### ISSUE TITLE
Cannot read property 'children' of undefined

### ISSUE THREAD

**Issue by PhantomCrestTV** [microlinkhq/spotify-url-info#68]
So, I've never used GitHub to report an issue until now. This Is rather quite irritating for me as my discord bot relies on this package. The full error im getting is this. I know it's not my code as I have tried someone else's working code. https://sourceb.in/dZ43ivbdRO

**Comment by henry-bao** [comment]
If you can, post the Discord bot's code too

**Comment by karlsander** [comment]
Hey, please post a spotify URL that is not working and if you can the part of your code that is using the module.
The error you posted is pretty generic and doesn't tell us anyhting.

That said, some of the tests for this library are failing right now so I will have a look at that.

**Comment by Kikobeats** [comment]
sorry, I can't debug with an easy way to reproduce the error
