### ISSUE TITLE
Is there any way to get more than 100 tracks?

### ISSUE THREAD

**Issue by ItzPray** [microlinkhq/spotify-url-info#73]
Is there any way to get more than 100 tracks?

**Comment by Kikobeats** [comment]
Sounds like a pretty generic question. Can you give us more context on this?

An example of a URL?

**Comment by ItzPray** [comment]
> Sounds like a pretty generic question. Can you give us more context on this?
> 
> An example of a URL?

I am trying to add a spotify playlist that has more than 100 songs in it. The limit for the amount of songs that can be got from the metadata is 100. I am wondering if there is any way I can get the extra songs that are not in the metadata.

**Comment by Kikobeats** [comment]
Hmm I don't know; if 100 comes from Spotify data that should be the limit for the preview on the browser
