### ISSUE TITLE
Bug: Missing index.d.ts in latest release

### ISSUE THREAD

**Issue by oceanroleplay** [microlinkhq/spotify-url-info#77]
**Describe the bug**

@Kikobeats In the latest release, index.d.ts is missing. Was this intentional or was it a mistake??

**Comment by oceanroleplay** [comment]
![image](https://user-images.githubusercontent.com/43092101/151682062-409c73f1-1b4b-4fe5-bdb0-de20b4b6de56.png)

**Comment by Kikobeats** [comment]
@oceanroleplay it was a mistake; can you confirm v2.2.5 fixed it?

**Comment by oceanroleplay** [comment]
yes, it's fixed now. Thanks
