### ISSUE TITLE
[BUG] TypeError: Cannot read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by MontiKasta** [microlinkhq/spotify-url-info#80]
**Describe the bug**
I did a few tries after the error popped up. I think if the first song in a playlist is an episode, there is an error in the artists part.

**Spotify URL(s)**
I created a playlist for you to check the error more easily 

First Track is Episode (Error) : https://open.spotify.com/playlist/0I4mmS9EzRzqaGaYZc4DqV
First Track is Song : https://open.spotify.com/playlist/277H1jS7KALrvJlKtrDbtN

**Error Message**
TypeError: Cannot read properties of undefined (reading 'map')

People who don't want a problem until the bug is fixed they can use the code like this :

```
const artist = track.artists ? track.artists.map(a => a.name).join(' & ') : undefined
  
  return Promise.resolve({
    date,
    title: data.name,
    type: data.type,
    track: track.name,
    description: data.description || undefined,
    artist: artist,
    image: images.reduce((a, b) => (a.width > b.width ? a : b)).url,
    audio: track.preview_url,
    link: data.external_urls.spotify,
    embed: `https://embed.spotify.com/?uri=${data.uri}`
  })
```

**Comment by Kikobeats** [comment]
Hello, and thanks for reporting!

I'm working to fix this now, hopefully it will be shipped in the next hours 🙂
