### ISSUE TITLE
Suggestion: ES Module import

### ISSUE THREAD

**Issue by nikosszzz** [microlinkhq/spotify-url-info#92]
Hello,

Is there a way to get any of these functions of this package using `import` as a module? I keep getting errors that it dont has named exports. I have a discord bot depending on this, so any help would be helpful.

**Comment by Kikobeats** [comment]
Hello, can you test v[3.1.1](https://github.com/microlinkhq/spotify-url-info/commit/8b9a5cacc8da3aafacc0395ae78a6f162c570126)? it should be fixed the error.

**Comment by nikosszzz** [comment]
``` 
import { spotifyUrlInfo } from "spotify-url-info";
         ^^^^^^^^^^^^^^
SyntaxError: Named export 'spotifyUrlInfo' not found. The requested module 'spotify-url-info' is a CommonJS module, which may not support all module.exports as named exports.        
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'spotify-url-info';
const { spotifyUrlInfo } = pkg;
```

Unfortunately, not fixed.

**Comment by Kikobeats** [comment]
did you try the suggestion?

```
import pkg from 'spotify-url-info';
const { spotifyUrlInfo } = pkg;
```

**Comment by nikosszzz** [comment]
Still not working, says it is not a function.
