### ISSUE TITLE
Browserify with spotify-url-info

### ISSUE THREAD

**Issue by dsbbl** [microlinkhq/spotify-url-info#93]
Hi! I'm trying to use browserify on the spotify-url-info but after transformation with browserify I'm reciving that error:

**Uncaught (in promise) TypeError: Couldn't parse 'https://open.spotify.com/track/4ywmyUAQ0WAdNHXpoWWqfv?si=d88e7b5f410c4a0c' as valid URL**

I know this link exists in the spotify. Do you have any ideas what went wrong?

**Comment by Kikobeats** [comment]
Hello, this is the code line related with that error:
https://github.com/microlinkhq/spotify-url-info/blob/master/src/index.js#L73=

Can you try to add some debug traces there?
