### ISSUE TITLE
Doesn't work anymore - Spotify changed their embeds.

### ISSUE THREAD

**Issue by Eithoo** [microlinkhq/spotify-url-info#94]
**Describe the bug**
Doesn't work anymore - Spotify changed their embeds.

**Spotify URL(s)**
https://open.spotify.com/track/0Q0IVlqMV64kNLlwjPj0Hl?si=1b161308512e453f
https://open.spotify.com/track/0nhVrTiCGiGRCoZOJiWzm1?si=6c51f98fcb4140f4

**Your Code**
![image](https://user-images.githubusercontent.com/62159998/187729736-b8dc4f76-8116-40d3-a286-b93b7e3b0c65.png)
**Error Message**
Error: Couldn't find any data in embed page that we know how to parse
![image](https://user-images.githubusercontent.com/62159998/187729911-2ecda874-a25e-4eeb-9c17-7997b7d7ad6e.png)

**Comment by CustomTag** [comment]
I think they changed something in there api let me check and get back to you

**Comment by CustomTag** [comment]
Yea i know what the problem is spotify changed there html text and data things after the new Embed update lets just wait for the package owner to update it

**Comment by CustomTag** [comment]
The best thing you can do now is by using spotify api to track the song data or wait till the owner updates the package
