### ISSUE TITLE
getPreview Does not return any data

### ISSUE THREAD

**Issue by NChemdok** [microlinkhq/spotify-url-info#97]
**Describe the bug**
the method getPreview() is unable to fetch the track details

**Spotify URL(s)**
tried with other track ids but doesnt work. Tried the deafult one on the github page, that also doesnt work.

**Your Code**
 getPreview("https://open.spotify.com/track/5nTtCOCds6I0PHMNtqelas").then(
    (data) => console.log(data)
  );

**Error Message**
(node:18204) UnhandledPromiseRejectionWarning: Error: Couldn't find any data in embed page that we know how to parse
    at D:\Projects\Discord\Manu Nahoi\node_modules\spotify-url-info\src\index.js:62:9

**Comment by Kikobeats** [comment]
It should be fixed at https://github.com/microlinkhq/spotify-url-info/releases/tag/v3.1.5

Can you confirm?

**Comment by NChemdok** [comment]
Yes. Working Perfectly now. :)
